name: Cleanup Obsidian Directory

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete .obsidian directories
        run: |
          echo "Checking for .obsidian directories..."
          if [ -d ".obsidian" ]; then
            echo "Deleting .obsidian directory..."
            rm -rf .obsidian
            echo ".obsidian directory deleted."
          else
            echo ".obsidian directory does not exist."
          fi

