name: Cleanup Obsidian Directory

on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  cleanup:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Delete .obsidian directory if it exists
        run: |
          echo "Checking for .obsidian directory..."
          if [ -d ".obsidian" ]; then
            echo "Deleting .obsidian directory..."
            rm -rf .obsidian
            echo ".obsidian directory deleted."
          else
            echo ".obsidian directory does not exist."
          fi

      - name: Commit changes if .obsidian was deleted
        run: |
          if [ ! -d ".obsidian" ]; then
            echo "Committing changes..."
            git config --local user.email "actions@github.com"  # GitHub Actions 机器人邮箱
            git config --local user.name "GitHub Action"
            git add -u  # 只添加已删除的文件
            git commit -m "Remove .obsidian directory from main branch"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 提供的 token

